services:
  - type: web
    name: screen-webrtc
    env: node
    rootDir: SCREEN
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables from your .env file here
    healthCheckPath: /api/hello
    autoDeploy: true 